show sidebar in campus edit form
kartoza/ford3 pull request #208
Opened 2019-04-10 05:23 UTC by boney-bun

fix #186

2019-04-10 05:26 UTC, boney-bun commented
PIA:
![ford3#186](https://user-images.githubusercontent.com/4602383/55853532-bcf0f300-5b8b-11e9-9807-14a9782803d4.gif)

2019-04-10 07:34 UTC, Christiaanvdm submitted a review, later dismissed
LGTM

2019-04-10 07:43 UTC, Christiaanvdm reviewed
I believe this will show the side-bar on the provider form as well which is unwanted.
I believe just adding this to the campus' javascript should be sufficient.

```
$(document).ready(function() {
    // Show sidebar
    toggleSidebar()
})

```

2019-04-11 06:05 UTC, pierrealixt commented
Why the name of the provider disappears?

2019-04-15 08:26 UTC, boney-bun commented
@Christiaanvdm i'm a bit confusing about the sidebar part.
the original codes seem to not working properly.
even in the test_widgets it's not working.

so i change the code in 8308d5f to using jquery instead of using HTML DOM property.

below is how the sidebar behave:
![ford3#208](https://user-images.githubusercontent.com/4602383/56117505-6708ba80-5f92-11e9-98cc-50c62322583f.gif)

notice that the sidebar always show up on detail pages, but hide on edit pages.
if this is the expected behaviour, then this issue is irrelevant.
or, do we want to make an exception to show the sidebar in the campus edit form ?

2019-04-15 11:43 UTC, Christiaanvdm commented on django_project/core/base_static/css/sidebar.css
> -    margin-left: -250px;
You need to undo this change for the sidebar.toggle() to work correctly.

2019-04-15 11:45 UTC, Christiaanvdm commented on django_project/core/base_static/js/sidebar.js
>  const toggleSidebar = () => {
I think if the CSS is reverted the JS doesnt need to be changed.

2019-04-15 17:46 UTC, boney-bun commented
hi @Christiaanvdm 
i think i'm a bit confused with the logic before.
i have returned the code into the original one and add campus.js into campus edit form.

2019-04-16 07:22 UTC, pierrealixt requested changes
![sidebar-campus-form](https://user-images.githubusercontent.com/35932320/56189798-1e501080-6029-11e9-8386-6000928372d0.gif)
The provider's name is not present in the sidebar...

2019-04-16 10:49 UTC, boney-bun commented
@pierrealixt the provider link is now show up in campus edit form:
![ford3#208revise](https://user-images.githubusercontent.com/4602383/56203712-f768fd00-606f-11e9-9f9a-c210ddf3e9c3.gif)

2019-04-17 06:04 UTC, pierrealixt approved these changes
LGTM

2019-04-18 05:22 UTC, boney-bun commented
thanks @pierrealixt 
i'm going to merge this

2019-04-18 05:23 UTC, merged