Give provider option to save postal address separately
kartoza/ford3 pull request #217
Opened 2019-04-14 20:54 UTC by Christiaanvdm

This closes #139 
![NewGIF](https://user-images.githubusercontent.com/34506346/56099029-4bf16880-5f08-11e9-9cbb-fbc31e16ddc9.gif)

2019-04-26 09:43 UTC, pierrealixt requested changes
LGTM
Please fix the conflicts and merge.

2019-05-01 04:33 UTC, Christiaanvdm commented
Any idea why these tests are failing @pierrealixt ? Working on my machine.

2019-05-01 21:15 UTC, pierrealixt commented
I don't know @Christiaanvdm

2019-05-01 21:15 UTC, pierrealixt approved these changes

2019-05-02 08:30 UTC, merged